version: "3.9"

services:
  web:
    build: .
    image: ricardomlima/{app_name}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/home
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DEBUG=True
      - HOST=0.0.0.0

  db:
    image: postgres:15.1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
