version: "3.9"
   
services:
  web:
    build: .
    image: ricardomlima/{app_name}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/home
    ports:
      - "8000:8000"